version: '3.5'

services:
  db_pharma:
    container_name: db_pharma
    image: mongo:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: pharma
    env_file: .env
    ports:
      - ${DB_PORT}:27017
    networks:
      - pharma
    volumes:
      - ./db/.dbshell:/home/mongodb/.dbshell
      - mongodb:/data/db
      - ./db/mongo.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  
  pharma_backend:
    depends_on:
      - db_pharma
    build: .
    container_name: pharma_backend
    ports:
      - ${APPLICATION_PORT}:8080
    env_file: .env
    networks:
      - pharma
    volumes:
      - ./:/code
    
volumes:
  mongodb:

networks:
  pharma:
    name: pharma
    driver: bridge